image: node:18

pipelines:
  default:
    - step:
        name: Build & Deploy Frontend
        caches:
          - node
        script:
          - cd frontend
          - npm install
          - npm run build
          - apt-get update && apt-get install -y openssh-client
          - echo "$EC2_SSH_KEY" > key.pem
          - chmod 400 key.pem
          - scp -o StrictHostKeyChecking=no -i key.pem -r dist/* ubuntu@<EC2_PUBLIC_IP>:/home/ubuntu/wotnot/frontend
    - step:
        name: Deploy FastAPI Backend
        script:
          - apt-get update && apt-get install -y openssh-client
          - echo "$EC2_SSH_KEY" > key.pem
          - chmod 400 key.pem
          - scp -o StrictHostKeyChecking=no -i key.pem -r backend ubuntu@<EC2_PUBLIC_IP>:/home/ubuntu/wotnot/backend
          - ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@<EC2_PUBLIC_IP> << EOF
              cd /home/ubuntu/wotnot/backend
              python3 -m venv venv
              source venv/bin/activate
              pip install --upgrade pip
              pip install -r requirements.txt
              nohup uvicorn wati.main:app --host 0.0.0.0 --port 8000 &
            EOF
