image: node:18

pipelines:
  branches:
    production:
      - step:
          name: Build & Deploy Frontend (Vue.js to S3)
          caches:
            - node
          script:
            - apt-get update && apt-get install -y awscli
            - cd frontend/app
            - npm install
            - npm run build
            - aws s3 sync dist/ s3://$S3_BUCKET --region $S3_REGION --delete    

  

