image: node:18

pipelines:
  branches:
    production:
      - step:
          name: Build & Deploy Frontend (Vue.js to S3)
          caches:
            - node
          script:
            - apt-get update && apt-get install -y awscli
            - cd frontend/app
            - npm install
            - npm run build
            - aws s3 sync dist/ s3://$S3_BUCKET --region $S3_REGION --delete --acl public-read   

      - step:
          name: Deploy Backend to EC2 via Docker Compose
          deployment: production
          script:
            - apt-get update && apt-get install -y openssh-client
            - mkdir -p ~/.ssh
            - echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
            - scp -r backend/* ubuntu@$EC2_HOST:/home/ubuntu/backend/
            - ssh ubuntu@$EC2_HOST 'cd /home/ubuntu/backend && docker-compose down && docker-compose up -d --build'

